n=int(input('So tien ban dau: '))
k=int(input('So thang gui: '))
T=float(input("Lai suat/thang: "))
m=n*(1+k*T)
print('Voi so tien ban dau',str(int(n))+str(','),"sau",k,"thang gui,","lai suat",str(float(T))+str('/'),'thang')
print('Thi so tien nhan duoc cuoi ky la:',m)